DROP SCHEMA IF EXISTS LIBRARY;
CREATE SCHEMA LIBRARY;

USE LIBRARY;

CREATE TABLE Publisher (
	`Name` VARCHAR(60) PRIMARY KEY NOT NULL,
    Address VARCHAR(120) NOT NULL,
    Phone VARCHAR(16) NOT NULL
);

CREATE TABLE BOOK (
	ISBN CHAR(13) PRIMARY KEY NOT NULL,
    Title VARCHAR(120) NOT NULL,
    Publisher VARCHAR(60) NOT NULL,
    Pub_Year YEAR NOT NULL,
    Price INT NOT NULL,
    Category ENUM('Science','Art','Religion','History','Geography'),
    Stock INT,
    Threshold INT,
    CONSTRAINT FK_BOOK_Publisher FOREIGN KEY (Publisher) REFERENCES Publisher(`Name`) 
);

CREATE TABLE AUTHOR (
	`Name` VARCHAR(60) NOT NULL,
    ISBN CHAR(13) NOT NULL,
    PRIMARY KEY(`Name`, ISBN),
    CONSTRAINT FK_AUTHOR_ISBN FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);

CREATE TABLE LIBRARY_ORDER (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ISBN CHAR(13) NOT NULL,
    Quantity INT NOT NULL,
    CONSTRAINT FK_LIBRARY_ORDER_ISBN FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);

CREATE TABLE `USER` (
	Username VARCHAR(20) PRIMARY KEY NOT NULL,
    Password CHAR(60) NOT NULL,
    FName VARCHAR(30) NOT NULL,
    LNAME VARCHAR(30) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    Phone VARCHAR(16) NOT NULL,
    Address VARCHAR(120) NOT NULL,
    Is_Manager BOOL NOT NULL
);

CREATE TABLE USER_ORDER (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Username VARCHAR(20) NOT NULL,
    Credit_Card_No CHAR(16),
    CVC CHAR(3),
    Expiry_Date DATE,
    CONSTRAINT FK_USER_ORDER_Username FOREIGN KEY (Username) REFERENCES `USER`(Username)
);

CREATE TABLE USER_ORDER_BOOKS (
	Id INT AUTO_INCREMENT NOT NULL,
    ISBN CHAR(13) NOT NULL,
    Quantity INT,
    CONSTRAINT PK PRIMARY KEY(Id, ISBN),
    CONSTRAINT FK_USER_ORDER_BOOKS_ISBN FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);

CREATE TABLE CREDIT_CARDS (
	Credit_Card_No CHAR(16) PRIMARY KEY NOT NULL,
    CVC CHAR(3) NOT NULL,
    Expiry_Date DATE NOT NULL,
    Balance INT NOT NULL DEFAULT 0
);