USE LIBRARY;

CREATE UNIQUE INDEX BOOK_ISBN_INDEX ON BOOK(ISBN);
CREATE INDEX BOOK_Title_INDEX ON BOOK(Title);
CREATE INDEX BOOK_Publisher_INDEX ON BOOK(Publisher);
CREATE INDEX BOOK_Pub_Year_INDEX ON BOOK(Pub_Year);
CREATE INDEX BOOK_Price_INDEX ON BOOK(Price);
CREATE INDEX BOOK_Stock_INDEX ON BOOK(Stock);
CREATE INDEX BOOK_Category_INDEX ON BOOK(Category);
CREATE INDEX BOOK_All_INDEX ON BOOK(ISBN, Title, Publisher, Pub_Year, Price, Category, Stock);
CREATE INDEX USER_USERNAME_INDEX ON `USER`(Username);